language: bash
os:
  - linux

branches:
  only:
    - master
    - /release-.*/

script:
  - "wolframscript -f Test.m"
  - "wolframscript -c '10!'"

notifications:
  email: false

cache:
  directories:
    - $HOME/.download/

before_install:
  - echo $HOME
  # download and install Wolfram Engine
  - |
    if [[ ! -f "$HOME/.download/WolframEngine.sh" ]]; then
      wget -O $HOME/.download/WolframEngine.sh https://account.wolfram.com/download/public/wolfram-engine/desktop/LINUX
    fi
  - printf "\n\n" | sudo bash $HOME/.download/WolframEngine.sh
  # information
  - WolframKernel -version
  - WolframKernel -machineid
  - which WolframKernel
  # activate
  - printf '\n${MATH_ACTIVATION_KEY}\n${MATH_PASSWORD}\n' | WolframKernel
