language: bash
os:
  - linux

branches:
  only:
    - master
    - /release-.*/

script: "wolframscript -f Test.m"

notifications:
  email: false

cache:
  directories:
    - $HOME/.download/

before_install:
  - echo $HOME
  # download and install Wolfram Engine
  - |
    if [[ -f "$HOME/.download/WolframEngine.sh" ]]; then
      wget -O $HOME/.download/WolframEngine.sh https://account.wolfram.com/download/public/wolfram-engine/desktop/LINUX
      exit 1
    fi
  - printf "\n\n" | sudo bash $HOME/.download/WolframEngine.sh
  # information
  - WolframKernel -version
  - WolframKernel -machineid
  - which WolframKernel
  # activate
  - printf '1001-1010-456789\n2039-378-645:8::20200630\n' | WolframKernel
