name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Wolfram Engine
        run: wget -O WolframEngine.sh https://account.wolfram.com/download/public/wolfram-engine/desktop/LINUX
      - name: Install Wolfram Engine
        run: printf "\n\n" | sudo bash WolframEngine.sh
      - name: Wolfram Engine Information
        run: |
          WolframKernel -version
          WolframKernel -machineid
      - name: Find Wolfram Engine
        run: which WolframKernel
      - name: Activate Wolfram Engine
        run: printf '\n${{ secrets.MATH_ACTIVATION_KEY }}\n${{ secrets.MATH_PASSWORD }}\n' | WolframKernel
      - name: Run Wolfram Example Script
        run: wolframscript -f SystemID.m
      - name: Run Wolfram Example Command
        run: wolframscript -c '10!'
      - name: Run Wolfram Example Compiler
        run: wolframscript -f Compile.m
